Ecom_show/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop.urls')),
    path('mysuperadmin/', include('myadmin.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name="Home"),
    path('checkout', views.checkout, name='CheckOut'),
    path('products/<int:id>', views.product_view, name='Product_View'),
    path('track_order', views.tracker, name='Tracker'),
]

Shop/models.py
from django.db import models
from datetime import date
# Create your models here.


class Product(models.Model):
    prod_id = models.AutoField
    prod_name = models.CharField(max_length=50,blank=True)
    category = models.CharField(max_length=50, default="")
    sub_category = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    prod_desc = models.CharField(max_length=300,blank=True)
    pub_date = models.DateField(auto_now_add=True)
    prod_image = models.ImageField(upload_to="Shop",blank=True)
    status = models.CharField(max_length=20,blank=True)



class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000)
    email = models.EmailField(max_length=50)
    name = models.CharField(max_length=90)
    amount = models.IntegerField(default=0)
    address = models.CharField(max_length=111)
    city = models.CharField(max_length=111)
    state = models.CharField(max_length=111)
    zip_code = models.CharField(max_length=111)
    phone = models.CharField(max_length=111, default="")
    order_date = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(max_length=20, blank=True)
    delivery_status = models.CharField(max_length=20, blank=True)
    delivery_date = models.DateTimeField(blank=True, null=True)
    remarks = models.CharField(max_length=200, blank=True)


class OrderUpdate(models.Model):
    update_id  = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateTimeField(auto_now_add=True)

Shop/forms.py

from django import forms  
from django.contrib.auth.models import User
from Shop.models import Product



class UpdateProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['prod_name','category','sub_category','price','prod_desc','status','prod_image']

Shop/views.py
from django.shortcuts import render, redirect, HttpResponse
from Shop.models import Product, Order, OrderUpdate
from math import ceil
import json
# Create your views here.


def index(request):
    allprods = []
    catprods = Product.objects.values('category','id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod = Product.objects.filter(category=cat,status="Active")
        if len(prod)==0:
            continue
        n = len(prod)
        nSlides = n//4 +ceil((n/4)-(n//4))
        allprods.append([prod,range(1,nSlides),nSlides])

    context = {
        'allprods':allprods
    }
    return render(request, 'index.html',context)


def checkout(request):
    id = None
    thank=False
    if request.method=="POST":
        items_json = request.POST.get('itemsJson', '')
        amount = request.POST.get('amount', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address1', '') + " " + request.POST.get('address2', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('pin_code', '')
        phone = request.POST.get('phone', '')
        order = Order(items_json=items_json,amount=amount,email=email, name=name, address=address, city=city,
                       state=state, zip_code=zip_code, phone=phone,order_status='Pending',delivery_status='Pending')
        order.save()
        thank = True
        id = order.order_id
        return render(request, 'checkout.html', {'thank':thank, 'id': id})        
    
    context = {
        'thank':thank, 
        'id': id
    }
    return render(request,'checkout.html',context)

def product_view(request,id):
   
    product = Product.objects.filter(id=id)
    
    context = {
        'product':product[0],
    }
    return render(request,'product_veiw.html',context)


def tracker(request):
    response = {}
    if request.method=="POST":
        orderId = request.POST.get('orderId', '')
        mobile = request.POST.get('mobile', '')
        try:
            order = Order.objects.filter(order_id=orderId)
    
            if len(order)>0 and order[0].phone == mobile:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                for item in update:
                    updates.append({'text': item.update_desc, 'time': item.timestamp})
                    # response = json.dumps([updates, order[0].items_json], default=str)
                    # print(response)
                    items = json.loads(order[0].items_json)
                    response = {
                        'updates':updates,
                        'items':items,
                        'order':order[0],
                    }
                # return HttpResponse(response)
            else:
                response = {
                    'msg':'Order Id or Mobile Number is incorrect. Please try again with correct details.'
                }
        except Exception as e:
            return HttpResponse('{}')


    return render(request, 'tracker.html', response)

templates/addproducts.html

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Hello, world!</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css'%}">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>
  <body>
    <nav id="header" class="navbar navbar-fixed-top">
        <div id="header-container" class="container navbar-container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
                </button>
                <a id="brand" class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="update_new">Home</a></li>
                    <li><a href="pending_order_None">Pending Order</a></li>
                    <li><a href="#contact">Contact</a></li>
                    
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li><a href="logout"><i class="fa fa-power-off" style="font-size:24px;color:red"></i></a></li>
                </ul>
            </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
    </nav><!-- /.navbar -->
<div class="container"></div>
{% block body %}
<div id="contentdiv" style="clear: both;">
    <div class="table-responsive bg-light">
        <div class="table_top" id="table_top">
            <form method="POST" class="post-form" enctype="multipart/form-data" action="/mysuperadmin/update_new">
                {% csrf_token %}
                <table style="float:left;" width="100%" align="center" cellpadding="0" cellspacing="0" class="table table-curved table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td align="center">
                                <div id="header">
                                    <span>Add New Product</span>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                               
                                <table width="100%" align="center" class="table table-bordered table-hover table-striped">
                                    <td  width="94%">
                                        <div class="form-group row"> 
                                            <label class="col-sm-3 col-form-label">Product Name</label>  
                                            <div class="col-sm-3">  
                                                <input type="text" class="form-control" name="prod_name" id="id_prod_name" value="{{item.prod_name}}" maxlength="50" required />     
                                            </div>  
                                            <label class="col-sm-3 col-form-label">Price</label>  
                                            <div class="col-sm-3">  
                                                <input type="number" class="form-control" name="price" id="id_price"  value="{{item.price}}" maxlength="50" required />     
                                            </div> 
                                        </div>

                                        <div class="form-group row">  
                                            <label class="col-sm-3 col-form-label">Category</label>  
                                            <div class="col-sm-3">  
                                                <input type="text" class="form-control" name="category" id="id_category"  value="{{item.category}}" maxlength="50" required />
                                            </div>  
                                            <label class="col-sm-3 col-form-label">Sub-Category</label>  
                                            <div class="col-sm-3"> 
                                                <input type="text" class="form-control" name="sub_category" id="id_sub_category"  value="{{item.sub_category}}" maxlength="50" required/>
                                               
                                            </div> 
                                        </div> 
                                        
                    
                                        <div class="form-group row">  
                                            <label class="col-sm-3 col-form-label">Descriptions</label>  
                                            <div class="col-sm-9">  
                                                <textarea type="text" class="form-control" name="prod_desc" id="id_prod_desc"  value="{{item.prod_desc}}" maxlength="300">{{item.prod_desc}}</textarea>
                                            </div>  
                                        </div>
                                        
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Status</label>  
                                            <div class="col-sm-3">  
                                                <select class="form-control" name="status" id="id_status" required />
                                                    <option value="{{item.status}}">{{item.status}}</option>
                                                    <option value="Active">Active</option>
                                                    <option value="Inactive">Inactive</option>
                                                </select>      
                                            </div>
                                            <label class="col-sm-3 col-form-label">Product Image</label>  
                                            <div class="col-sm-3">  
                                                <input id="id_imageUpload" type="file" name="prod_image" placeholder="Photo" capture>      
                                            </div> 
                                        </div>  
                                                <input type="hidden" class="form-control" name="id" id="id_id"  value="{{item.id}}" />      
                                    </td>           
                                </table>
                                <table width="100%" cellpadding="0" cellspacing="0" border="0" class="head1" >
                                    <tr>
                                        <div class="form-group row" >
                                            <div class="col-sm-7"></div>
                                            <div class="col-sm-5">
                                                <button style="border:none;" type="submit" value="Submit">
                                                    <a class="btn" style="background-color: green;">Submit</a>
                                                </button>

                                                <a class="btn btn-primary" style="background-color: yellow; color: black;" href="/mysuperadmin/update_new">New</a>
                                            </div>
                                        </div>
                                    </tr> 
                                    <tr></tr>
                                </table> 
                            </td>
                    
                        </tr>
                    </tbody>
                </table>
            </form>
            
        </div>   
    </div>
    

    
        

    <center><h4><b>Product List</b></h4></center>
   
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th style="text-align:center">Edit</th>
                <th style="text-align:center">SL No.</th>
                <th style="text-align:center">Product Name</th>
                <th style="text-align:center">Product Price</th>
                <th style="text-align:center">Category</th>
                <th style="text-align:center">Sub Category</th>
                <th style="text-align:center">Image</th>
                <th style="text-align:center">Status</th>
                <th style="text-align:center">Date</th>
                <th style="text-align:center">Descriptions</th>
                
             

            </thead>
            <tbody>
            {% for product in products %}  
                <tr>  
                    <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/mysuperadmin/update_{{ product.id }}" class=" btn-primary btn-xs" data-title="Edit" ><span class="glyphicon glyphicon-pencil"></span></a></p></td>
                    <td style="text-align:center">{{ forloop.counter }}</td> 
                    <td style="text-align:center">{{ product.prod_name }}</td>  
                    <td style="text-align:center">{{ product.price }}</td>  
                    <td style="text-align:center">{{ product.category }}</td>  
                    <td style="text-align:center">{{ product.sub_category }}</td> 
                    <td style="text-align:center"><img id="slip_image_{{ product.prod_id }}" src="/media/{{ product.prod_image }}" width="30px;" height="30px" onclick="window.open('/media/{{ product.prod_image }}', '_blank');"><span id="error_{{ product.prod_id }}"></span> </td>  
                    <script>
                        var img = document.getElementById("slip_image_{{ product.prod_id }}");
                        img.onerror = function () { 
                            this.style.display = "none";
                            document.getElementById("error_{{ product.prod_id }}").innerHTML='None'
                        }
                    </script> 
                    <td style="text-align:center">{{ product.status }}</td>
                    <td style="text-align:center; width: 100px;">{{ product.pub_date|date:'j-M-Y' }}</td>  
                    <td style="text-align:center">{{ product.prod_desc }}</td>    

                </tr>  
                {% endfor %} 
            </tbody>
     
        </table>

    </div>

</div>

{% endblock body %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">




<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready(function(){

var myNavBar = {

    flagAdd: true,

    elements: [],

    init: function (elements) {
        this.elements = elements;
    },

    add : function() {
        if(this.flagAdd) {
            for(var i=0; i < this.elements.length; i++) {
                document.getElementById(this.elements[i]).className += " fixed-theme";
            }
            this.flagAdd = false;
        }
    },

    remove: function() {
        for(var i=0; i < this.elements.length; i++) {
            document.getElementById(this.elements[i]).className =
                    document.getElementById(this.elements[i]).className.replace( /(?:^|\s)fixed-theme(?!\S)/g , '' );
        }
        this.flagAdd = true;
    }

};


/**
 * Init the object. Pass the object the array of elements
 * that we want to change when the scroll goes down
 */
myNavBar.init(  [
    "header",
    "header-container",
    "brand"
]);

/**
 * Function that manage the direction
 * of the scroll
 */
function offSetManager(){

    var yOffset = 0;
    var currYOffSet = window.pageYOffset;

    if(yOffset < currYOffSet) {
        myNavBar.add();
    }
    else if(currYOffSet == yOffset){
        myNavBar.remove();
    }

}

/**
 * bind to the document scroll detection
 */
window.onscroll = function(e) {
    offSetManager();
}

/**
 * We have to do a first detectation of offset because the page
 * could be load with scroll down set.
 */
offSetManager();
});
</script>
{% block js%}
<script>

    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({     
          "aLengthMenu": [[5, 10, 20, 50,100, -1], [5, 10, 20, 50,100, "All"]],
            "iDisplayLength": 5
           } 
        );
    } );
    $(document).ready(function() {
        $('#bootstrapdatatabl').DataTable({     
          "aLengthMenu": [[5, 10, 20, 50,100, -1], [5, 10, 20, 50,100, "All"]],
            "iDisplayLength": 20
           } 
        );
    } );
    
</script>
{% endblock js%}

</body>
</html> 

templates/adminlogin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Admin Login</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <style>
        body {
            background: #000 !important;
        }
        .card {
            border: 1px solid #28a745;
        }
        .card-login {
            margin-top: 130px;
            padding: 18px;
            max-width: 30rem;
        }

        .card-header {
            color: #fff;
            /*background: #ff0000;*/
            font-family: sans-serif;
            font-size: 20px;
            font-weight: 600 !important;
            margin-top: 10px;
            border-bottom: 0;
        }

        .input-group-prepend span{
            width: 50px;
            background-color: #ff0000;
            color: #fff;
            border:0 !important;
        }

        input:focus{
            outline: 0 0 0 0  !important;
            box-shadow: 0 0 0 0 !important;
        }

        .login_btn{
            width: 130px;
        }

        .login_btn:hover{
            color: #fff;
            background-color: #ff0000;
        }

        .btn-outline-danger {
            color: #fff;
            font-size: 18px;
            background-color: #28a745;
            background-image: none;
            border-color: #28a745;
        }

        .form-control {
            display: block;
            width: 100%;
            height: calc(2.25rem + 2px);
            padding: 0.375rem 0.75rem;
            font-size: 1.2rem;
            line-height: 1.6;
            color: #28a745;
            background-color: transparent;
            background-clip: padding-box;
            border: 1px solid #28a745;
            border-radius: 0;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        .input-group-text {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding: 0.375rem 0.75rem;
            margin-bottom: 0;
            font-size: 1.5rem;
            font-weight: 700;
            line-height: 1.6;
            color: #495057;
            text-align: center;
            white-space: nowrap;
            background-color: #e9ecef;
            border: 1px solid #ced4da;
            border-radius: 0;
        }
    </style>

  </head>
  <body>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
<div class="container">
    <div class="card card-login mx-auto text-center bg-dark">
        <div class="card-header mx-auto bg-dark">
            <!-- <span> <img src="https://amar.vote/assets/img/amarVotebd.png" class="w-75" alt="Logo"> </span><br/> -->
                        <span class="logo_title mt-5"> Admin Login </span>


        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token%} 
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" name="user_id" class="form-control" placeholder="Admin ID" required />
                </div>

                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" name="password" class="form-control" placeholder="Password" required />
                </div>

                <div class="form-group">
                    <input type="submit" name="btn" value="Login" class="btn btn-outline-danger float-right login_btn">
                </div>

            </form>
        </div>
    </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/checkout.html
{% extends 'index.html' %}

{% block css %}

{% endblock css %}

{% block body %}
<a href="/" type="button" class="btn btn-info" style="text-decoration:none; float: right; width: fit-content;">Shopping More</a>
  
<div class="bg-light my-5">
   
       
    <div class="col-sm-12 col-md-8 my-4">
        <h4>Review Your Cart Items:</h4>
        <div class="col-sm-12 col-md-12 my-4">
            <ul class="list-group" id="items"></ul>
            <div class="mx-4" style="float:right;">Total : <span style="color:red">&#8377;<span id="totalPrice"></span></span></div>
        </div>
    </div>
    <div class="col-sm-12 col-md-8 my-4">
        <h4>Shipping Details:</h4>
        <form method="post" action="/checkout">
            {% csrf_token %}
            <div class="col-md-12">
            <input type="hidden" name="itemsJson" id="itemsJson">
            <input type="hidden" name="amount" id="amount">
            
                <div class="form-group">
                    <label for="inputname">Full Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{member.full_name}}" required>
                </div>
                
            
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="address1" name="address1" placeholder="Address" value="{{member.address}}" required>
            </div>
        
            <div class="form-row">
                <div class="form-group col-md-5">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="city" name="city" placeholder="City" value="{{member.city}}" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" name="state"  placeholder="State" value="{{member.state}}" required>
                </div>
                <div class="form-group col-md-3">
                    <label for="inputZip">PIN</label>
                    <input type="text" class="form-control" id="pin_code" name="pin_code" placeholder="PIN" value="{{member.pincode}}" required>
                </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
                <label for="input number">Phone Number</label>
                <input type="tel" class="form-control" id="phone" name="phone"placeholder="Phone Number" maxlength="10" value="{{member.contact}}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="input number">Email</label>
                <input type="email" class="form-control" id="email" name="email"placeholder="Email" value="{{member.email}}">
            </div>
            </div>
            <button type="submit" id="order_button" class="btn btn-primary">Place Order</button>
        </div>
        </form>
    </div>
</div>


{% endblock body %}

{% block js %}
<script>
    if (localStorage.getItem('cart') == null) {
        var cart = {};
    } else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    var sum = 0;
    var totalPrice = 0;
    if ($.isEmptyObject(cart)) {
        //if object is empty
        mystr = `<p>Your cart is empty, please add some items to your cart before checking out!</p>`
        $('#items').append(mystr);
        $('#order_button').prop('disabled', true);
    } else {
        for (item in cart) {
            let name = cart[item][1];
            let qty = cart[item][0];
            let itemPrice = cart[item][2];
            sum = sum + qty;
            totalPrice = totalPrice + qty*itemPrice;
            itemtotalPrice = qty*itemPrice;
            mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                        ${name}
                        <span class="badge">Qty: ${qty}</span>
                        <span class="badge">&#8377;${itemPrice}</span>
                        <span class="badge" style="color:blue;">&#8377;${itemtotalPrice}</span>
                    </li>` 
            $('#items').append(mystr);
            $('#order_button').prop('disabled', false);
        }
    }
    document.getElementById('cart').innerHTML = sum;
    document.getElementById('totalPrice').innerHTML = totalPrice;
    $('#itemsJson').val(JSON.stringify(cart));
    {% if thank %}
    alert('Thanks for ordering with us. Your Order-Id is {{id}}.');
    localStorage.clear();
    document.location = "/";
    {% endif %}
    $('#amount').val($('#totalPrice').html())
    </script>
    
{% endblock js %}

templates/product_veiw.html
{% extends 'index.html' %}


{% block body %}
{% load static %}
<div class="container bg-light">
<a href="/" class="nav" style="text-decoration:none; width:auto; background: transparent;" ><span class="nav-link" style="width: fit-content;" >Shopping Home</span></a> 
<!-- <a href="/products" class="nav" style="text-decoration:none; width:auto; background: transparent;" ><span class="nav-link" style="width: fit-content;" >Product List</span></a>  -->
</div>
<div class="container bg-light">
    
    <div class="row">
        <div class="col-md-4">
            <div class="img-row mx-4">
                <img src="/media/{{product.prod_image}}" width="260px" height="320px">
            </div>
        
        </div>
        <div class="col-md-8">
            <h5>{{product.prod_name}}</h5>
            <p><b>&#8377; {{product.price}}</b></p>
            <p>{{product.prod_desc}}</p>
            <!-- <div class="row mx-4">
                <span id="addpr{{product.id}}" class="addpr" style='width: auto;'>
                <button id="pr{{product.id}}" class="btn btn-primary cart">Add to Cart</button></span>
                
            </div> -->
           <a type="button" class="btn btn-outline-danger" href="/">Back</a>
        </div>
        
    </div>
    
</div>


{% endblock body %}

{% block js %}

<script src="{% static '/js/cart.js' %}"></script>
{% endblock js %}